### ISSUE TITLE
Helm workflow should lint using latest Helm version (as warning, not as failure)

### ISSUE THREAD

**Issue by bfjelds** [deislabs/akri#120]
**Is your feature request related to a problem? Please describe.**
When a new Helm version is released, sometimes its lint capabilities change and it can pick up new things.

It would be great to run the latest linting so that we can see if a potential issue arises.  At the same time, I don't think it would make sense to fail a PR CI build because of this.  There isn't a Github actions concept that allows for a failure to exist without causing a CI workflow to fail (and show up as a failure in the PR page) ... but there are Github actions Issues about enabling `allow-failure` for a workflow: 

* https://github.com/actions/toolkit/issues/399
* https://github.com/actions/runner/issues/798

It is not clear if/when/where this will land.

In the meantime, until there is a way for a Github workflow to just "warn" on failure, we can play with the actual lint command ... we could change the existing Helm workflow like this:

```yaml
jobs:
  lint-with-current-helm:
    # Run workflow pull_request if it is NOT a fork, as pull_request_target if it IS a fork
    if: >-
      ( github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.fork == true ) ||
      ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false )
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout the merged commit from PR and base branch
        uses: actions/checkout@v2
        if: github.event_name == 'pull_request_target'
        with:
          # pull_request_target is run in the context of the base repository
          # of the pull request, so the default ref is master branch and
          # ref should be manually set to the head of the PR
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      - name: Checkout the head commit of the branch
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2

      - uses: azure/setup-helm@v1

      - name: Lint helm chart
        run: helm lint deployment/helme && echo "lint finished successfully" || echo "lint found issues"


  helm:
    # existing flow here
```
