### ISSUE TITLE
Automate dependency upgrades

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#184]
**Is your feature request related to a problem? Please describe.**

Akri comprises 4 members and each member comprises a list of crate dependencies. It is moderately important that Akri be kept current with its dependencies but it already drifts quite considerably (e.g. `kube` uses [`0.23.0`](https://crates.io/crates/kube/0.23.0) published 30-Dec-2019 current is [`0.46.0`](https://crates.io/crates/kube/0.46.0) published 02-Jan-2021).

Outdated dependencies potentially:

+ include security vulnerabilities
+ are feature poorer
+ accrue technical debt.

Additionally, it is important to prune no-longer-needed dependencies in order to reduce:

+ code-size
+ attack surface
+ complexity in managing dependencies.

Members:

```TOML
members = [
    "shared",
    "controller",
    "agent",
    "samples/brokers/udev-video-broker"
]
```

Agent's `Cargo.toml`:

```TOML
[dependencies]
async-stream = "0.2"
async-trait = "0.1.0"
blake2 = "0.8.0"
chrono = "0.4.10"
cfg-if = "0.1"
env_logger = "0.6.1"
failure = "0.1.5"
futures = { version = "0.3.1", package = "futures" }
futures-core = "0.3"
futures-util = "0.3"
futures-old = { version = "0.1", package = "futures" }
hyper = "0.11"
kube = { version = "0.23.0", features = ["openapi"] }
k8s-openapi = { version = "0.6.0", features = ["v1_16"] }
log = "0.4"
mime = "0.3"
mockall = "0.6.0"
pest = "2.0"
pest_derive = "2.0"
prost = "0.6"
rand = "0.7"
regex = "1"
serde = "1.0.104"
serde_json = "1.0.45"
serde_yaml = "0.8.11"
serde_derive = "1.0.104"
akri-shared = { path = "../shared" }
sxd-document = "0.3.0"
sxd-xpath = "0.4.0"
tempfile = "3.1.0"
tokio = { version = "0.2", features = ["full"] }
tokio-core = "0.1"
tokio-test = "0.3.0"
tonic = "0.1"
tower = "0.3" 
udev = "0.4"
uuid = { version = "0.8.1", features = ["v4"] }
xml-rs = "0.8.0"
yaserde = "0.3.13"
yaserde_derive = "0.3.13"
zeroconf = "0.6.2"

[build-dependencies]
tonic-build = "0.1.1"
```

**Is your feature request related to a way you would like Akri extended? Please describe.**

N/A

**Describe the solution you'd like**

The Akri project may wish to consider a(n automated) build process in which dependencies are:

+ pruned as appropriate; only include those that are explicit, current dependencies
+ upgraded to the latest (major+minor) versions to see "Will it build?" and remedial actions indicated when it doesn't

**Describe alternatives you've considered**

N/A

**Additional context**

E.g. see https://github.com/deislabs/akri/issues/180#issuecomment-754220329
