### ISSUE TITLE
Represent Akri API version of CRDs in Helm chart

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#200]
**Is your feature request related to a problem? Please describe.**

Akri's Helm chart does not provide constants for the API version of its CRDs: `apiVersion: akri.sh/v0`

[Admission Webhooks](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) to control these CRDs are defined in terms of them:

```YAML
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: ...
webhooks:
  - ...
    rules:
      - operations:
          - "CREATE"
          - "UPDATE"
        apiGroups:
          - "akri.sh"
        apiVersions:
          - "v0"
        resources:
          - "configurations"
        scope: "*"
    ...
```

To avoid, hard-coding these values, propose adding `Values.yaml` root section entries as these may be useful elsewhere:

```YAML
crds:
- group: "akri.sh"
  version: "v0"
  kinds:
  - configurations
  - instances
```

Preference on the hierarchy? Alternative:

```YAML
crds:
- name: configurations
  group: akri.sh
  version: v0
- name: instances
  group: akri.sh
  version: v0
```

**Describe alternatives you've considered**

Represent these constants in the `webhook` section in `Values.yaml`

**Additional context**
