### ISSUE TITLE
Include Akri Configurations|Instances in `kubectl get all ...`

### ISSUE THREAD

**Issue by DazWilkin** [deislabs/akri#268]
**Is your feature request related to a problem? Please describe.**

Akri's CRDs (Configurations and Instances) aren't included in `kubectl get all`.

This command, while possibly overused, is a good way to get a snapshot of resources in a namespace.

Because CRDs are less-common resource types and because these are (by definition) non-standard Kubernetes resources, it's not always obvious that they exist.

Currently, when using `kubectl get all ...` with Akri, Pods, Services, DaemonSet, Deployments (and ReplicaSets) are enumerated. The developer must be familiar with CRDs to know that they can:

```bash
kubectl get configurations --namespace=${NAMESPACE}
NAME        CAPACITY   AGE
akri-http   1          20h

kubectl get instances --namespace=${NAMESPACE}
NAME               CONFIG      SHARED   NODES              AGE
akri-http-0d65a6   akri-http   true     ["hades-canyon"]   20h
akri-http-1daa25   akri-http   true     ["hades-canyon"]   20h
akri-http-286fb9   akri-http   true     ["hades-canyon"]   20h
akri-http-31f1eb   akri-http   true     ["hades-canyon"]   20h
```

**Is your feature request related to a way you would like Akri extended? Please describe.**

I propose including Akri's CRDs in `kubectl get all ....` commands.

Making this change, `kubectl get all ...` will enumerate: Pods, Sevices, DaemonSets, Deployments (and ReplicaSets), Akri Instances and Akri Configurations.

**Describe the solution you'd like**

I learned recently that there is a `categories` property on [`CustomResourceDefinitionsNames`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#customresourcedefinitionnames-v1-apiextensions-k8s-io) that permits inclusion of CRDs in `kubectl get all`.

This should (!?) be a straightforward tweak to Akri's CRDs (defined in the Helm Chart):

https://github.com/deislabs/akri/blob/6bab87c0fd382d0c883faf4f35ac4b985d48f483/deployment/helm/crds/akri-configuration-crd.yaml#L137

```YAML
  names:
    plural: configurations
    singular: configuration
    kind: Configuration
    shortNames:
    - akric
    categories:
    - all
```

https://github.com/deislabs/akri/blob/6bab87c0fd382d0c883faf4f35ac4b985d48f483/deployment/helm/crds/akri-instance-crd.yaml#L53

```YAML
  names:
    plural: instances
    singular: instance
    kind: Instance
    shortNames:
    - akrii
    categories:
    - all
```

**Describe alternatives you've considered**

I would consider submitting this as a PR but I'm unsure whether it will break anything else and so proposing here for your consideration.

**Additional context**
