### ISSUE TITLE
Resource limit quantity type

### ISSUE THREAD

**Issue by jiria** [deislabs/akri#99]
**Is your feature request related to a problem? Please describe.**
Akri Configuration resource limit quantity is specified as string:
```
 resources:
          limits:
            "{{PLACEHOLDER}}": "1"
```
But if you look at Device Plugin Kubernetes doc page, the quantity is numeric, not a string: https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/
```
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: demo-container-1
      image: k8s.gcr.io/pause:2.0
      resources:
        limits:
          hardware-vendor.example/foo: 2
```

**Describe the solution you'd like**
Consider using numeric quantity.
